tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#24657e",
        "on-primary": "#ffffff",
        "primary-container": "#8ecae6",
        "on-primary-container": "#0a566e",
        "primary-fixed": "#bde9ff",
        "primary-fixed-dim": "#93cfeb",
        "on-primary-fixed": "#001f2a",
        "on-primary-fixed-variant": "#004d64",
        "secondary": "#43664d",
        "on-secondary": "#ffffff",
        "secondary-container": "#c2e9c9",
        "on-secondary-container": "#486a51",
        "secondary-fixed": "#c5eccc",
        "secondary-fixed-dim": "#aad0b1",
        "on-secondary-fixed": "#00210e",
        "on-secondary-fixed-variant": "#2c4e36",
        "tertiary": "#605f50",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#c5c2b0",
        "on-tertiary-container": "#515042",
        "tertiary-fixed": "#e6e3d0",
        "tertiary-fixed-dim": "#c9c7b5",
        "on-tertiary-fixed": "#1c1c11",
        "on-tertiary-fixed-variant": "#48473a",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "background": "#f8f9fa",
        "on-background": "#191c1d",
        "surface": "#f8f9fa",
        "surface-dim": "#d9dadb",
        "surface-bright": "#f8f9fa",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f4f5",
        "surface-container": "#edeeef",
        "surface-container-high": "#e7e8e9",
        "surface-container-highest": "#e1e3e4",
        "surface-variant": "#e1e3e4",
        "surface-tint": "#24657e",
        "on-surface": "#191c1d",
        "on-surface-variant": "#40484c",
        "outline": "#70787d",
        "outline-variant": "#c0c8cd",
        "inverse-surface": "#2e3132",
        "inverse-on-surface": "#f0f1f2",
        "inverse-primary": "#93cfeb",
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem",
        "2xl": "1rem", "3xl": "1.5rem", "full": "9999px"
      },
    },
  },
}
